//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ExamNature { get; set; }
        public string ExamId { get; set; }
        public string VoucherId { get; set; }
        public string CandidateId { get; set; }
        public string ExamStatus { get; set; }
        public Nullable<short> Attempts { get; set; }
        public Nullable<System.DateTime> ExamDatel { get; set; }
        public string EmailAddress { get; set; }
        public string ExamEmailAddress { get; set; }
        public string ExamEmailPassword { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public Nullable<int> AcademyId { get; set; }
    
        public virtual academy academy { get; set; }
        public virtual exam exam { get; set; }
        public virtual institute institute { get; set; }
        public virtual voucher voucher { get; set; }
    }
}
