//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.exams = new HashSet<exam>();
            this.vouchers = new HashSet<voucher>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsAcademic { get; set; }
    
        public virtual ICollection<exam> exams { get; set; }
        public virtual ICollection<voucher> vouchers { get; set; }
    }
}
