//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.exams = new HashSet<exam>();
            this.examcodes = new HashSet<examcode>();
            this.pricings = new HashSet<pricing>();
            this.purchasingpricings = new HashSet<purchasingpricing>();
            this.mails = new HashSet<mail>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsAcademic { get; set; }
    
        public virtual ICollection<exam> exams { get; set; }
        public virtual ICollection<examcode> examcodes { get; set; }
        public virtual ICollection<pricing> pricings { get; set; }
        public virtual ICollection<purchasingpricing> purchasingpricings { get; set; }
        public virtual ICollection<mail> mails { get; set; }
    }
}
