//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class sadiqEntities1 : DbContext
    {
        public sadiqEntities1()
            : base("name=sadiqEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<academy> academies { get; set; }
        public DbSet<candidate> candidates { get; set; }
        public DbSet<client> clients { get; set; }
        public DbSet<confighiredprometric> confighiredprometrics { get; set; }
        public DbSet<exam> exams { get; set; }
        public DbSet<institute> institutes { get; set; }
        public DbSet<mail> mails { get; set; }
        public DbSet<prometric> prometrics { get; set; }
        public DbSet<voucher> vouchers { get; set; }
    
        public virtual int GetMailDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMailDetails");
        }
    }
}
