//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class complimentaryvoucher
    {
        public complimentaryvoucher()
        {
            this.vouchers = new HashSet<voucher>();
        }
    
        public int BatchId { get; set; }
        public string BatchNo { get; set; }
        public string Type { get; set; }
        public Nullable<int> Nature { get; set; }
        public string ClientId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ICollection<voucher> vouchers { get; set; }
    }
}
