//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class examstraining
    {
        public examstraining()
        {
            this.trainingaccounts = new HashSet<trainingaccount>();
        }
    
        public int Id { get; set; }
        public string ExamId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TrainingCost { get; set; }
        public Nullable<int> TotalAmountReceived { get; set; }
        public Nullable<int> TrainerID { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual trainer trainer { get; set; }
        public virtual ICollection<trainingaccount> trainingaccounts { get; set; }
    }
}
