//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public exam()
        {
            this.candidates = new HashSet<candidate>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ClientId { get; set; }
    
        public virtual ICollection<candidate> candidates { get; set; }
        public virtual client client { get; set; }
    }
}
