//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public exam()
        {
            this.pearsoncandidates = new HashSet<pearsoncandidate>();
            this.examstrainings = new HashSet<examstraining>();
        }
    
        public string Id { get; set; }
        public string ExamNo { get; set; }
        public string ClientId { get; set; }
        public string Title { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<pearsoncandidate> pearsoncandidates { get; set; }
        public virtual ICollection<examstraining> examstrainings { get; set; }
    }
}
