//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class examnature
    {
        public examnature()
        {
            this.vouchers = new HashSet<voucher>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<voucher> vouchers { get; set; }
    }
}
