//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail
    {
        public int Id { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string CandidateName { get; set; }
        public string ExamNo { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<bool> Abroad { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> CommittedPrice { get; set; }
        public string StudentMailId { get; set; }
        public string client { get; set; }
    
        public virtual institute institute { get; set; }
        public virtual client client1 { get; set; }
    }
}
