//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class prometricpromotion
    {
        public int id { get; set; }
        public Nullable<int> SiteId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public Nullable<int> MarginGain { get; set; }
        public Nullable<int> MarginMiss { get; set; }
    
        public virtual prometric prometric { get; set; }
    }
}
