//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class techcentreadmin
    {
        public techcentreadmin()
        {
            this.prometrics = new HashSet<prometric>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SecurityQuestion1 { get; set; }
        public string AnswerQuestion1 { get; set; }
        public string SecurityQuestion2 { get; set; }
        public string AnswerQuestion2 { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<prometric> prometrics { get; set; }
    }
}
