//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingaccount
    {
        public int Id { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public Nullable<int> TrainingAmountReceived { get; set; }
        public Nullable<int> TrainingCostIncurred { get; set; }
    
        public virtual examstraining examstraining { get; set; }
    }
}
