//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainer
    {
        public trainer()
        {
            this.examstrainings = new HashSet<examstraining>();
        }
    
        public int TrainerID { get; set; }
        public string TrainerName { get; set; }
        public Nullable<int> TrainerPhone { get; set; }
    
        public virtual ICollection<examstraining> examstrainings { get; set; }
    }
}
