//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        public voucher()
        {
            this.candidates = new HashSet<candidate>();
        }
    
        public string Id { get; set; }
        public string Vendor { get; set; }
        public string Type { get; set; }
        public Nullable<int> Nature { get; set; }
        public string ClientId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public Nullable<bool> IsComplimentaryVoucher { get; set; }
        public Nullable<int> Price { get; set; }
        public string VoucherNo { get; set; }
        public string Batch { get; set; }
    
        public virtual ICollection<candidate> candidates { get; set; }
        public virtual client client { get; set; }
        public virtual examnature examnature { get; set; }
    }
}
