//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        public voucher()
        {
            this.pearsoncandidates = new HashSet<pearsoncandidate>();
            this.prometriccandidates = new HashSet<prometriccandidate>();
        }
    
        public string Id { get; set; }
        public string Vendor { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> BatchId { get; set; }
    
        public virtual complimentaryvoucher complimentaryvoucher { get; set; }
        public virtual ICollection<pearsoncandidate> pearsoncandidates { get; set; }
        public virtual ICollection<prometriccandidate> prometriccandidates { get; set; }
    }
}
